[project]
name = "ruuvi-opc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncua>=1.1.6",
    "ruuvitag-sensor>=3.1.0",
]
